### ISSUE TITLE
"major position change not significant"

### ISSUE THREAD

**Issue by theo-bittencourt** [mattleonard/tinder_across_america#2]
Hi!

I'm not using your lib, but I'm receiving that message too.
Have you found something more about it?

Best!

**Comment by icodeforlove** [comment]
They seem to have a basic check for distance so if the change is over X distance then the change is major, and major changes can only happen after X minutes.

I wouldn't be surprised if they tightened up the check to factor in the max speed someone can travel from X to Y and make that the limit. This is how online games lock down location change.
